SAMPLE_TIME = 0.1
RISK_OF_COLLISION_DISTANCE = 1.5
MAX_DISTANCE_TO_TARGET = 10
PROXIMITY_RANGE = 30 - 3

CONSTANT_MOTION_LINEAR_SPEED = 1
CONSTANT_MOTION_ANGULAR_VELOCITY = 1

BOUNDARY_FOLLOWING_LINEAR_SPEED = 3
BOUNDARY_FOLLOWING_ANGULAR_VELOCITY = 3
BOUNDARY_FOLLOWING_MAX_FREE_SPACE = 1.25
BOUNDARY_FOLLOWING_MIN_FREE_SPACE = 1

MOTION_TO_GOAL_LINEAR_SPEED = 3
MOTION_TO_GOAL_ANGULAR_VELOCITY = 3
MOTION_TO_GOAL_TRAJECTORY_CORRECTION_INTERVAL = 2

BUG_2_LINE_TOLERANCE = 0.5
BUG_2_INITIAL_POSITION_TOLERANCE = 1
