// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_to_environment.proto

#ifndef PROTOBUF_msg_5fto_5fenvironment_2eproto__INCLUDED
#define PROTOBUF_msg_5fto_5fenvironment_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msg_5fto_5fenvironment_2eproto();
void protobuf_AssignDesc_msg_5fto_5fenvironment_2eproto();
void protobuf_ShutdownFile_msg_5fto_5fenvironment_2eproto();

class MsgToEnvironment;

// ===================================================================

class MsgToEnvironment : public ::google::protobuf::Message {
 public:
  MsgToEnvironment();
  virtual ~MsgToEnvironment();

  MsgToEnvironment(const MsgToEnvironment& from);

  inline MsgToEnvironment& operator=(const MsgToEnvironment& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgToEnvironment& default_instance();

  void Swap(MsgToEnvironment* other);

  // implements Message ----------------------------------------------

  MsgToEnvironment* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgToEnvironment& from);
  void MergeFrom(const MsgToEnvironment& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float linear_velocity = 1;
  inline bool has_linear_velocity() const;
  inline void clear_linear_velocity();
  static const int kLinearVelocityFieldNumber = 1;
  inline float linear_velocity() const;
  inline void set_linear_velocity(float value);

  // required float angular_velocity = 2;
  inline bool has_angular_velocity() const;
  inline void clear_angular_velocity();
  static const int kAngularVelocityFieldNumber = 2;
  inline float angular_velocity() const;
  inline void set_angular_velocity(float value);

  // required bool reset_environment = 3;
  inline bool has_reset_environment() const;
  inline void clear_reset_environment();
  static const int kResetEnvironmentFieldNumber = 3;
  inline bool reset_environment() const;
  inline void set_reset_environment(bool value);

  // @@protoc_insertion_point(class_scope:MsgToEnvironment)
 private:
  inline void set_has_linear_velocity();
  inline void clear_has_linear_velocity();
  inline void set_has_angular_velocity();
  inline void clear_has_angular_velocity();
  inline void set_has_reset_environment();
  inline void clear_has_reset_environment();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  float linear_velocity_;
  float angular_velocity_;
  bool reset_environment_;
  friend void  protobuf_AddDesc_msg_5fto_5fenvironment_2eproto();
  friend void protobuf_AssignDesc_msg_5fto_5fenvironment_2eproto();
  friend void protobuf_ShutdownFile_msg_5fto_5fenvironment_2eproto();

  void InitAsDefaultInstance();
  static MsgToEnvironment* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgToEnvironment

// required float linear_velocity = 1;
inline bool MsgToEnvironment::has_linear_velocity() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgToEnvironment::set_has_linear_velocity() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgToEnvironment::clear_has_linear_velocity() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgToEnvironment::clear_linear_velocity() {
  linear_velocity_ = 0;
  clear_has_linear_velocity();
}
inline float MsgToEnvironment::linear_velocity() const {
  // @@protoc_insertion_point(field_get:MsgToEnvironment.linear_velocity)
  return linear_velocity_;
}
inline void MsgToEnvironment::set_linear_velocity(float value) {
  set_has_linear_velocity();
  linear_velocity_ = value;
  // @@protoc_insertion_point(field_set:MsgToEnvironment.linear_velocity)
}

// required float angular_velocity = 2;
inline bool MsgToEnvironment::has_angular_velocity() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgToEnvironment::set_has_angular_velocity() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgToEnvironment::clear_has_angular_velocity() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgToEnvironment::clear_angular_velocity() {
  angular_velocity_ = 0;
  clear_has_angular_velocity();
}
inline float MsgToEnvironment::angular_velocity() const {
  // @@protoc_insertion_point(field_get:MsgToEnvironment.angular_velocity)
  return angular_velocity_;
}
inline void MsgToEnvironment::set_angular_velocity(float value) {
  set_has_angular_velocity();
  angular_velocity_ = value;
  // @@protoc_insertion_point(field_set:MsgToEnvironment.angular_velocity)
}

// required bool reset_environment = 3;
inline bool MsgToEnvironment::has_reset_environment() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgToEnvironment::set_has_reset_environment() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgToEnvironment::clear_has_reset_environment() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgToEnvironment::clear_reset_environment() {
  reset_environment_ = false;
  clear_has_reset_environment();
}
inline bool MsgToEnvironment::reset_environment() const {
  // @@protoc_insertion_point(field_get:MsgToEnvironment.reset_environment)
  return reset_environment_;
}
inline void MsgToEnvironment::set_reset_environment(bool value) {
  set_has_reset_environment();
  reset_environment_ = value;
  // @@protoc_insertion_point(field_set:MsgToEnvironment.reset_environment)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_5fto_5fenvironment_2eproto__INCLUDED
