// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_to_environment.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "gz_environment/msg_to_environment.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MsgToEnvironment_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgToEnvironment_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_msg_5fto_5fenvironment_2eproto() {
  protobuf_AddDesc_msg_5fto_5fenvironment_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msg_to_environment.proto");
  GOOGLE_CHECK(file != NULL);
  MsgToEnvironment_descriptor_ = file->message_type(0);
  static const int MsgToEnvironment_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgToEnvironment, linear_velocity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgToEnvironment, angular_velocity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgToEnvironment, reset_environment_),
  };
  MsgToEnvironment_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MsgToEnvironment_descriptor_,
      MsgToEnvironment::default_instance_,
      MsgToEnvironment_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgToEnvironment, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgToEnvironment, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MsgToEnvironment));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msg_5fto_5fenvironment_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MsgToEnvironment_descriptor_, &MsgToEnvironment::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_msg_5fto_5fenvironment_2eproto() {
  delete MsgToEnvironment::default_instance_;
  delete MsgToEnvironment_reflection_;
}

void protobuf_AddDesc_msg_5fto_5fenvironment_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\030msg_to_environment.proto\"`\n\020MsgToEnvir"
    "onment\022\027\n\017linear_velocity\030\001 \002(\002\022\030\n\020angul"
    "ar_velocity\030\002 \002(\002\022\031\n\021reset_environment\030\003"
    " \002(\010", 124);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msg_to_environment.proto", &protobuf_RegisterTypes);
  MsgToEnvironment::default_instance_ = new MsgToEnvironment();
  MsgToEnvironment::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msg_5fto_5fenvironment_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msg_5fto_5fenvironment_2eproto {
  StaticDescriptorInitializer_msg_5fto_5fenvironment_2eproto() {
    protobuf_AddDesc_msg_5fto_5fenvironment_2eproto();
  }
} static_descriptor_initializer_msg_5fto_5fenvironment_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MsgToEnvironment::kLinearVelocityFieldNumber;
const int MsgToEnvironment::kAngularVelocityFieldNumber;
const int MsgToEnvironment::kResetEnvironmentFieldNumber;
#endif  // !_MSC_VER

MsgToEnvironment::MsgToEnvironment()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MsgToEnvironment)
}

void MsgToEnvironment::InitAsDefaultInstance() {
}

MsgToEnvironment::MsgToEnvironment(const MsgToEnvironment& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MsgToEnvironment)
}

void MsgToEnvironment::SharedCtor() {
  _cached_size_ = 0;
  linear_velocity_ = 0;
  angular_velocity_ = 0;
  reset_environment_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgToEnvironment::~MsgToEnvironment() {
  // @@protoc_insertion_point(destructor:MsgToEnvironment)
  SharedDtor();
}

void MsgToEnvironment::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgToEnvironment::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgToEnvironment::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgToEnvironment_descriptor_;
}

const MsgToEnvironment& MsgToEnvironment::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_5fto_5fenvironment_2eproto();
  return *default_instance_;
}

MsgToEnvironment* MsgToEnvironment::default_instance_ = NULL;

MsgToEnvironment* MsgToEnvironment::New() const {
  return new MsgToEnvironment;
}

void MsgToEnvironment::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<MsgToEnvironment*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(linear_velocity_, reset_environment_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MsgToEnvironment::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MsgToEnvironment)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required float linear_velocity = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &linear_velocity_)));
          set_has_linear_velocity();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_angular_velocity;
        break;
      }

      // required float angular_velocity = 2;
      case 2: {
        if (tag == 21) {
         parse_angular_velocity:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &angular_velocity_)));
          set_has_angular_velocity();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_reset_environment;
        break;
      }

      // required bool reset_environment = 3;
      case 3: {
        if (tag == 24) {
         parse_reset_environment:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &reset_environment_)));
          set_has_reset_environment();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MsgToEnvironment)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MsgToEnvironment)
  return false;
#undef DO_
}

void MsgToEnvironment::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MsgToEnvironment)
  // required float linear_velocity = 1;
  if (has_linear_velocity()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->linear_velocity(), output);
  }

  // required float angular_velocity = 2;
  if (has_angular_velocity()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->angular_velocity(), output);
  }

  // required bool reset_environment = 3;
  if (has_reset_environment()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->reset_environment(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MsgToEnvironment)
}

::google::protobuf::uint8* MsgToEnvironment::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MsgToEnvironment)
  // required float linear_velocity = 1;
  if (has_linear_velocity()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->linear_velocity(), target);
  }

  // required float angular_velocity = 2;
  if (has_angular_velocity()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->angular_velocity(), target);
  }

  // required bool reset_environment = 3;
  if (has_reset_environment()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->reset_environment(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MsgToEnvironment)
  return target;
}

int MsgToEnvironment::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required float linear_velocity = 1;
    if (has_linear_velocity()) {
      total_size += 1 + 4;
    }

    // required float angular_velocity = 2;
    if (has_angular_velocity()) {
      total_size += 1 + 4;
    }

    // required bool reset_environment = 3;
    if (has_reset_environment()) {
      total_size += 1 + 1;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgToEnvironment::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MsgToEnvironment* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgToEnvironment*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgToEnvironment::MergeFrom(const MsgToEnvironment& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_linear_velocity()) {
      set_linear_velocity(from.linear_velocity());
    }
    if (from.has_angular_velocity()) {
      set_angular_velocity(from.angular_velocity());
    }
    if (from.has_reset_environment()) {
      set_reset_environment(from.reset_environment());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MsgToEnvironment::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgToEnvironment::CopyFrom(const MsgToEnvironment& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgToEnvironment::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void MsgToEnvironment::Swap(MsgToEnvironment* other) {
  if (other != this) {
    std::swap(linear_velocity_, other->linear_velocity_);
    std::swap(angular_velocity_, other->angular_velocity_);
    std::swap(reset_environment_, other->reset_environment_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MsgToEnvironment::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgToEnvironment_descriptor_;
  metadata.reflection = MsgToEnvironment_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
