# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_to_agent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_to_agent.proto',
  package='',
  serialized_pb=_b('\n\x12msg_to_agent.proto\"Q\n\nMsgToAgent\x12\x17\n\x0bobservation\x18\x01 \x03(\x02\x42\x02\x10\x01\x12\x0e\n\x06reward\x18\x02 \x02(\x02\x12\x0c\n\x04\x64one\x18\x03 \x02(\x08\x12\x0c\n\x04info\x18\x04 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MSGTOAGENT = _descriptor.Descriptor(
  name='MsgToAgent',
  full_name='MsgToAgent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='observation', full_name='MsgToAgent.observation', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='reward', full_name='MsgToAgent.reward', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='done', full_name='MsgToAgent.done', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='MsgToAgent.info', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['MsgToAgent'] = _MSGTOAGENT

MsgToAgent = _reflection.GeneratedProtocolMessageType('MsgToAgent', (_message.Message,), dict(
  DESCRIPTOR = _MSGTOAGENT,
  __module__ = 'msg_to_agent_pb2'
  # @@protoc_insertion_point(class_scope:MsgToAgent)
  ))
_sym_db.RegisterMessage(MsgToAgent)


_MSGTOAGENT.fields_by_name['observation'].has_options = True
_MSGTOAGENT.fields_by_name['observation']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
